# SQL Server
db.sqlserver.host=localhost
db.sqlserver.port=1433
db.sqlserver.database=SmartWMS
db.sqlserver.user=sa
db.sqlserver.password=1234

# H2 local fallback
db.h2.url=jdbc:h2:file:./wms-local;AUTO_SERVER=TRUE